### DISCUSSION TITLE
How to specify error location

### DISCUSSION THREAD

**Discussion by gk12277** [stoplightio/spectral#1663] [Q&A] [answered]
Hi everyone,
I want to show error when `special_key` is missing from the yaml file

```yaml
foo:
  special_key:
    - abcd
```

This is my spectral ruleset

```yaml
  special_key_missing:
    description:
      Special Key missing
    severity: error
    given: "$[*]"
    then:
      field: special_key
      function: truthy
```

This works fine and shows error when key is missing but the problem is error is shown in all lines.

[![enter image description here][1]][1]

How can I show the error at a specific line suppose in this case I want to show it at topmost level at `foo` key

  
![image](https://user-images.githubusercontent.com/41449598/121292727-0ffb9780-c908-11eb-954b-afbdde0577c6.png)
