### DISCUSSION TITLE
How to handle this use case using built in core functions

### DISCUSSION THREAD

**Discussion by gk12277** [stoplightio/spectral#1754] [Q&A]
Hi, could someone help me out with this.

```yaml
type: object
properties:
    object_1:
       type: object
       properties:
           foo:
              property_1:
                      x_key: true
                      y_key: true
           bar:
              property_2:
                      y_key: true
```

In this example I want to check the casing for `object_1` properties when `x_key` is present.
That is casing for `foo` property should be checked since inside foo inside property_1 there is `x_key` and since
property_2 does not have `x_key` casing for it should not be checked. Can I handle this without writing a custom function fo this.

**Comment by P0lip** [comment]
Hey!
I think this should be possible.

```yaml
rules:
  valid-case:
    given: "$.properties.object_1.properties..x_key^^"
    then:
      field: "@key"
      function: casing
      functionOptions:
        type: pascal
```
I believe the above should work.
