### DISCUSSION TITLE
Did they way custom function load change from 5.9.2 to 6.1.0

### DISCUSSION THREAD

**Discussion by DFog14** [stoplightio/spectral#1902] [Q&A]
Heyoh,

We're trying to move our pipeline from Spectral v5.9.2 over to v6.1.0, but it  seems our custom functions no longer load on v6.1.0 despite being error free on v5.9.2.
Specifically what is happening is that the first rule that makes reference to one of our functions is Error-ing out with the following:
Error at #/rules/path-elements-should-not-contain-textual-references/then: must have required property 'function'

Our "then: section for that particular rule is unchanged from v5 to v6 and looks like the following:
```
path-elements-should-not-contain-textual-references:
  description: path elements should not contain textual references
  given: $.paths
  severity: warn
  recommended: true
  then:
    function: "pathElements"
    functionOptions:
      notInclude: "text"
```

Thank you in advance

**Comment by P0lip** [comment]
The example you have should be fine. Do you have `pathElements` listed among `functions`?

**Reply by DFog14** [reply]
We certainly do. Our .spectral.yml file is completely unchanged from version to version except for the v5 to v6 migration syntax changes. It looks like the following for our functions section:
```
functionsDir: "./functions"
functions:
  - pathElements
  - pathCasing
  - responseContent
  - etc...
```

**Reply by P0lip** [reply]
Hmm, that is interesting.
It seems like a bug to me.
Would it be possible for you to create a small reproducible example?
If not, could you send the whole ruleset?
You drop me an email at jakub(at)stoplight.io if it contains some sensitive information you wouldn't like to disclose publicly.

**Reply by DFog14** [reply]
Submitting the whole ruleset is a bit of an ask, as it spans about 50+ separate files in several nest directories. I'll see about getting together a smaller example this week.
I'm not sure if this is somehow related to #1821 that was closed out recently, but it seems to be a similar behavior.

**Reply by P0lip** [reply]
> Submitting the whole ruleset is a bit of an ask, as it spans about 50+ separate files in several nest directories. I'll see about getting together a smaller example this week.

Ah, I see. Hold on then - I can hand you over a version with more verbose logging if that's possible.
Would that work?

**Reply by DFog14** [reply]
I stripped down our rule set to a more streamlined example to demonstrate the issue. Attached is a zip.
[example.zip](https://github.com/stoplightio/spectral/files/7400832/example.zip)


If there's a way to enable more verbose logging during the rule set load, I'd be very appreciative if you could share that.

**Reply by P0lip** [reply]
Hey!
You need to add the following bit to `sww-rules.yml`
```yaml
functionsDir: "./funcs"
functions:
  - pathElements
```

LMK if that worked.

You may see `Cannot read property 'notInclude' of null` when you run it because it seems like you don't pass options in here

```yaml
  oas3-path-elements-should-not-contain-sww-references:
    description: path elements should not contain sww references
    given: $.paths
    severity: warn
    recommended: true
    then:
      function: "pathElements"
```
You should add some to make the error go away.

Hopefully that helps!
