### DISCUSSION TITLE
Check for Tags?

### DISCUSSION THREAD

**Discussion by michaelcilibrasi** [stoplightio/spectral#1944] [Q&A] [answered]
How can I check for tags not being present? I can check for tags having values. For example,
`paths[*]..summary`
shows me the value of the summary tags that are present. But I want to check if the summary tag itself is missing. For example, in the code snippet below, I want an error because it does not have a summary tag.

```
paths:
  /pets:
    get:
      operationId: listPets
      description: A description here.
      tags:
        - pets
```

**Comment by P0lip** [comment, marked as answer]
Hello! Would the following work?
```yaml
rules:
  summary-tag-defined:
    given: $.paths[*][get,post,put,delete,patch,trace,options,head]
    then:
      field: summary
      function: defined
 ```
