### DISCUSSION TITLE
Available tokens in regex processor

### DISCUSSION THREAD

**Discussion by htadashi** [stoplightio/spectral#1964] [Q&A] [answered]
Does Spectral supports word boundaries (i.e. the token `\b`) detection in its pattern function?

Tried to use the following rule to detect "e-mail" in any description field and it seems to break after using \b in the pattern:
```
rules:
  path-params: off
  e-mail-in-description:
    description: Should use email instead of e-mail in descriptions
    severity: warn
    given: "$..*[?(@property === 'description')]"	
    then:
      function: pattern
      functionOptions:
        notMatch: "\be-mail\b"
```

Thanks for all support and the team for developing such useful tool!
