### DISCUSSION TITLE
Rule to look at two different section in the API schema

### DISCUSSION THREAD

**Discussion by pemba-sherpa-sage** [stoplightio/spectral#2205] [Q&A]
I am trying to write a rule where I need to look at the property name at two different levels (one directly under schema and another one under Properties). The rule should make sure if `x-mappedTo` ( Cat in the below example) exists in the schema level, the properties should have x-mappedTo as well and vice-versa. Has anyone written a similar kind of rule? I am looking for ideas.

```yaml
components:
      Pet:
        type: object
        x-mappedTo: Cat. <----
        properties:
          id:
            type: integer
            format: int64
            x-mappedTo: CatId.  <----
          name:
            type: string
            x-mappedTo: CatName     <----
````
