### DISCUSSION TITLE
Override to turn off specific oas3-unused-component warning?

### DISCUSSION THREAD

**Discussion by clydecutting** [stoplightio/spectral#2220] [Q&A]
I'm volunteering on FDX (financialdataexchange.org) APIs which have two intentionally-defined but unused (within the yaml) entities. How can I create an override to turn off that warning or downgrade to info? I've tried this ruleset:

```yaml
extends: [[spectral:oas, all]]
overrides:
  files:
    - "API/fdxapi.consent.yaml"
  rules:
    oas3-unused-component:
      given:
        - "$.components/schemas/ConsentRequest"
      severity: info
```

Which gives me:

``` shell
clydecutting@Clydes-MBP fdxapi % spectral lint --ruleset  config/spectral-ruleset.yaml API/fdxapi.consent.yaml --verbose
Error running Spectral!
Error #1: [object Object]
```

Without the override (ruleset just `extends: [[spectral:oas, all]]`) we get:

```shell
/opt/atlassian/pipelines/agent/build/API/fdxapi.consent.yaml
 267:20  warning  oas3-unused-component  Potentially unused component has been detected.  components.schemas.ConsentRequest
```

**Comment by pavelkornev** [comment]
Try this:
```
extends: [[spectral:oas, all]]
overrides:
  files:
    - "API/fdxapi.consent.yaml"
  rules:
    oas3-unused-component: off
```

or
```
extends: [[spectral:oas, all]]
overrides:
  files:
    - "API/fdxapi.consent.yaml"
  rules:
    oas3-unused-component: info
```
