### DISCUSSION TITLE
spetral rule set function for value is not equal to somethig

### DISCUSSION THREAD

**Discussion by jmgamboa** [stoplightio/spectral#2226] [Q&A]
I am trying to ensure the selected path is **not**  certain value as opposed to exist within a given set of values
```
...
given: $.path.value
function: enumeration
then:
   field: @key 
   function: enumeration
   - instead of equal to this, not equal to this 


```
would i need to do a custom function for this?
