### DISCUSSION TITLE
I wish there were a simpler way to configure a custom rule to operate on any schema node

### DISCUSSION THREAD

**Discussion by jedwards1211** [stoplightio/spectral#2463] [General]
Admittedly I'm new to this and may not know how to do something, but I went to look at the `oas3-valid-schema-example` rule to see how it's configured to only operate on schemas, and I was surprised that it does that using complicated JSONPath operations:

```
      given: [
        "$.components.schemas..[?(@property !== 'properties' && @ && (@ && @.example !== void 0 || @.default !== void 0) && (@.enum || @.type || @.format || @.$ref || @.properties || @.items))]",
        "$..content..[?(@property !== 'properties' && @ && (@ && @.example !== void 0 || @.default !== void 0) && (@.enum || @.type || @.format || @.$ref || @.properties || @.items))]",
        "$..headers..[?(@property !== 'properties' && @ && (@ && @.example !== void 0 || @.default !== void 0) && (@.enum || @.type || @.format || @.$ref || @.properties || @.items))]",
        "$..parameters..[?(@property !== 'properties' && @ && (@ && @.example !== void 0 || @.default !== void 0) && (@.enum || @.type || @.format || @.$ref || @.properties || @.items))]",
      ],
```

I wish I could just say something like `nodeTypes: ['schema']` instead of using these complicated filter paths.

According to the company I work for many customers use the OpenAPI any schema `{}` by mistake instead of actually meaning any schema, and I'd like to make a lint rule to warn about that unless they add an explicit `x-any: true` marker property.  But matching objects that are schemas without any validation properties with JSONPaths isn't going to be straightforward.

Before discovering spectral I had started writing my own lint tool from scratch using some of my company's own traversal tools that made it easy to target any schema nodes, and it was a lot easier.

**Comment by cuttingclyde** [comment]
I tried to use these aliases to get to schema nodes:
```
aliases:
  PathItem:
    - $.paths[*]
  OperationObject:
    - "#PathItem[get,put,post,delete,options,head,patch,trace]"
  ResponseSchemas:
    - $.components.responses[*].content.application/json.schema
    - "#OperationObject.responses[*].content.application/json.schema"
  RequestSchemas:
    - "#OperationObject.requestBody.content.application/json.schema"
```

It works locally, but I get these errors when running in Bitbucket pipeline. Any idea why?

```
Error at #/aliases/RequestSchemas: the value of an alias must be a valid JSON Path expression or a reference to the existing Alias optionally paired with a JSON Path expression subset
Error at #/aliases/ResponseSchemas: the value of an alias must be a valid JSON Path expression or a reference to the existing Alias optionally paired with a JSON Path expression subset
```
