### DISCUSSION TITLE
How to alphabetically order all paths?

### DISCUSSION THREAD

**Discussion by shreyasbharath** [stoplightio/spectral#2530] [Q&A]
I've tried 👇🏽 , which doesn't work. Any ideas?

```
  openapi-paths-alphabetical:
    description: OpenAPI object should have alphabetical `paths`.
    message: '{{property}} should be ordered alphabetically'
    severity: error
    given: $.paths[*]~
    then:
      field: operation
      function: alphabetical
```

Also tried this, but it still errors after ordering the paths.

```
paths-alphabetical:
    description: OpenAPI should have alphabetical `paths`.
    recommended: true
    given: "$"
    then:
      field: paths
      function: alphabetical
      functionOptions:
        keyedBy: name
 ```

**Comment by shreyasbharath** [comment]
For posterity, this works:

```
 openapi-paths-alphabetical:
    description: OpenAPI object should have alphabetical `paths`.
    message: '{{property}} should be ordered alphabetically'
    recommended: true
    severity: error
    given: "$"
    then:
      field: paths
      function: alphabetical
 ```
