### DISCUSSION TITLE
Implementing "OR" with the rulesets

### DISCUSSION THREAD

**Discussion by pkonopacki1** [stoplightio/spectral#2584] [Q&A]
Sounds like a dumb question but somehow I never found how to do it. Basically I need to check if an object contains "field1" or "field2". I see that core functions implement "XOR" but not "OR". Is there some easy way to do it?

**Comment by james-asher** [comment]
The following is working for me:

Spectral Rule
```
rules:
  Exists_Test:
    description: Test if info.contact object has a 'one' or 'two' field... must have at least one. It is OK if it has both.
    message: Field Test for anyOf ['one', 'two'] failed. Must have at least one.
    severity: error
    given:  
      - $.info.contact
    then:
      function: schema
      functionOptions:
        schema:
          anyOf:
          - required: ['one']
          - required: ['two']
```

Use the following YAML to test.  Un-comment the elements `one` and `two` to test the rule accuracy.

```
openapi: 3.0.0
info:
  version: 1.0.0
  title: Your Favorite API
  description: A simple OR test.
  contact:
    # one: "yes"
    # two: "no"
    name: Daisy
    email: Daisy@YourCo.com
    url: https://YourCo.com/
```
