### ISSUE TITLE
Can't show more than one message from a custom function, even though the response is an array

### ISSUE THREAD

**Issue by RobPhippen** [stoplightio/spectral#1030]
**Describe the bug**
Custom functions can return an array of objects, but only the first element can be displayed.

**To Reproduce**
1. Create this function, called `functions/fail_func.js`
``` javascript
module.exports = (targetVal) => {
    return [
      {
        message: 'Message 1',
      },
      {
        message: 'Message 2',
      },
    ]
};
```

2. Create this function definition in `.spectral.yml`
``` yaml
functions:
  - fail_func

rules:
  fail-rule:
    description: Hope to show two errors
    given: $
    severity: error
    message: "{{error}}"
    then:
      function: fail_func
```

3. Run `spectral lint myopenapi.yaml`
Get message
```
 1:1  error  fail-rule   Message 1
```

**Expected behavior**
at step 3, I expect to see both 'Message 1' and 'Message 2'

**Comment**
If that is **not** the expected behaviour, then perhaps the response from a custom function should not be an array?
