### ISSUE TITLE
Regex in pattern property is incorrectly parsed

### ISSUE THREAD

**Issue by nicexe** [stoplightio/spectral#1115]
**Describe the bug**
Regex patterns aren't correctly parsed and as a result, valid examples for properties get flagged as non-matching.

**To Reproduce**

1. Here is a schema snippet of an OpenAPI 3 specification:
```yaml
date-of-birth:
  type: string
  format: date
  example: '1991-04-12'
  pattern: '/^(19|20)[0-9]{2}-(0[1-9]|1[0-2])-(0[0-9]|[1-2][0-9]|3[0-1])$/'
```
2. Stoplight Studio flags this as an issue saying:
```
`example` property pattern should match pattern `/^(19|20)[0-9]{2}-(0[1-9]|1[0-2])-(0[0-9]|[1-2][0-9]|3[0-1])$/`
```

**Expected behavior**
The pattern follows the OpenAPI 3 spec which should be in this form ([as per spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#schema-object)): [ECMA 262 regular expression](https://www.ecma-international.org/ecma-262/5.1/#sec-7.8.5) and therefore it shouldn't be flagged as an issue.

**Environment (remove any that are not applicable):**
 - Library version: 5.0.0
 - OS: Windows 10
 - Browser: Stoplight Studio 1.11.0

**Comment by nulltoken** [comment]
@nicexe From what I've tested (not through Studio, but through Spectral itself), it will work if you drop the forward slashes that wrap the regex.

```
date-of-birth:
  type: string
  format: date
  example: '1991-04-12'
  pattern: '^(19|20)[0-9]{2}-(0[1-9]|1[0-2])-(0[0-9]|[1-2][0-9]|3[0-1])$'
```

FWIW, the OAS3 schema itself doesn't enclose the regex within slashes

![image](https://user-images.githubusercontent.com/92363/80069105-16328700-8541-11ea-9c22-994b2d038071.png)
