### ISSUE TITLE
Support OR combinator

### ISSUE THREAD

**Issue by XVincentX** [stoplightio/spectral#1276]
It would be very helpful if Spectral could support some sort of OR combinator where I can define multiple functions to apply. If one of them passes, the validation is marked as ✅ 

```
  given: >-
      $...parameters[*].name
  then:
    or:
    - function: casing
      functionOptions:
        type: snake
    - function: casing
      functionOptions:
        type: camel
```
