### ISSUE TITLE
Custom function not working

### ISSUE THREAD

**Issue by alexrainman** [stoplightio/spectral#1342]
I am following the [documentation](https://meta.stoplight.io/docs/spectral/docs/guides/5-custom-functions.md) to create custom functions.

My function is on the functions/ folder and look like this:

```js
module.exports = (targetVal) => {
    var responses = Object.keys(targetVal);
    if (!responses.includes("401")) {
      return [
        {
          message: 'operations must define a 401 response.',
        },
      ];
    }
  };
```

And my custom rule looks like this:

```yml
operation-success-response:
    description: "Operations must define a 401 response."
    recommended: true
    given: $.paths.*[?( @property === 'get' || @property === 'put' || @property === 'post' || @property === 'delete' || @property === 'options' || @property === 'head' || @property === 'patch' || @property === 'trace' )]
    then:
      - field: responses
        function: oasOpResponse401Required
```

What is missing?
