### ISSUE TITLE
Rule to validate tag count

### ISSUE THREAD

**Issue by danielbecroft** [stoplightio/spectral#1693]
I'm trying to configure some custom rules in our environment, and using the `operation-singular-tag` example from the documentation [here](https://meta.stoplight.io/docs/spectral/docs/reference/functions.md#length).

```yaml
extends: [[ spectral:oas, off ]]

rules:
  operation-singular-tag:
    description: Operations must have between 1 and 3 tags.
    type: style
    given: "$.paths.*"
    then:
      field: tags
      function: length
      functionOptions:
        max: 3
        min: 1
```

When I run the ruleset, though, I don't get the rule firing. I've tried on paths with:
- 0 tags
- 1 tag
- 10 tags

I can see in the `-v` mode that the rule is getting picked up.

```
Found 56 rules (1 enabled)
Linting ......openapi.yaml
OpenAPI 3.x detected
No results with a severity of 'info' or higher found!
```

Am I missing anything obvious? This is the first custom rule I'm adding in.
