### ISSUE TITLE
exclusiveMinimum must be a number thrown for OpenAPI 3.0

### ISSUE THREAD

**Issue by icubbon** [stoplightio/spectral#1894]
https://github.com/stoplightio/spectral/issues/1752 was verified to work in spectra-rulesets-v1.2.2 but when using spectra-rulesets-v1.2.5, the failure exists again. The same example and the same procedure from issue #1752 still applies.

**Comment by P0lip** [comment]
Hey!
I gave this is a try using the latest version, and it works fine for me.
Are you sure you're on the 1.2.5?

**Comment by icubbon** [comment]
Pretty sure, I am not an expert though.
Contents of `node_modules/@stoplight/spectral-rulesets/package.json`
```
{
  "_from": "@stoplight/spectral-rulesets@v1.2.5",
  "_id": "@stoplight/spectral-rulesets@1.2.5",
  "_inBundle": false,
  "_integrity": "sha512-i7DIE7g+1zPeX4SXzo3dwZhAihMQ9YNs71zNUzCf6ketW1K5u3pbNZE3ew44IS8s7X44DbbgseX/agkXTk9N9g==",
  "_location": "/@stoplight/spectral-rulesets",
  "_phantomChildren": {},
  "_requested": {
    "type": "version",
    "registry": true,
    "raw": "@stoplight/spectral-rulesets@v1.2.5",
    "name": "@stoplight/spectral-rulesets",
    "escapedName": "@stoplight%2fspectral-rulesets",
    "scope": "@stoplight",
    "rawSpec": "v1.2.5",
    "saveSpec": null,
    "fetchSpec": "v1.2.5"
  },
  "_requiredBy": [
    "#USER",
    "/",
    "/@stoplight/spectral",
    "/@stoplight/spectral-ruleset-bundler"
  ],
  "_resolved": "https://registry.npmjs.org/@stoplight/spectral-rulesets/-/spectral-rulesets-1.2.5.tgz",
  "_shasum": "952347880019a683a9a2c594d698becd58b1ab04",
  "_spec": "@stoplight/spectral-rulesets@v1.2.5",
  "_where": "/home/ianc/go/src/github.com/SpectraLogic/lumos",
  "author": {
    "name": "Stoplight",
    "email": "support@stoplight.io"
  },
  "bugs": {
    "url": "https://github.com/stoplightio/spectral/issues"
  },
  "bundleDependencies": false,
  "dependencies": {
    "@stoplight/better-ajv-errors": "0.2.0",
    "@stoplight/json": "3.17.0",
    "@stoplight/spectral-core": "^1.3.0",
    "@stoplight/spectral-formats": "^1.0.1",
    "@stoplight/spectral-functions": "^1.1.2",
    "@stoplight/spectral-runtime": "^1.0.0",
    "@stoplight/types": "^12.3.0",
    "@types/json-schema": "^7.0.7",
    "ajv": "~8.6.0",
    "ajv-formats": "~2.1.0",
    "json-schema-traverse": "^1.0.0",
    "lodash": "~4.17.21",
    "tslib": "^2.3.0"
  },
  "deprecated": false,
  "devDependencies": {
    "@stoplight/path": "^1.3.2",
    "@stoplight/spectral-parsers": "*",
    "@stoplight/spectral-ref-resolver": "*",
    "immer": "^9.0.6"
  },
  "engines": {
    "node": ">=12"
  },
  "files": [
    "/dist"
  ],
  "homepage": "https://github.com/stoplightio/spectral",
  "license": "Apache-2.0",
  "main": "dist/index.js",
  "name": "@stoplight/spectral-rulesets",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/stoplightio/spectral.git"
  },
  "types": "dist/index.d.ts",
  "version": "1.2.5"
}
```
Output from `spectral --version` -> `6.1.0`

Output from the Lint:
```
2486:15    error  oas3-valid-schema-example  exclusiveMinimum value must be ["number"]                                    components.schemas.BackupSettings.example
4653:17    error  oas3-valid-schema-example  schema is invalid: data/properties/interval/exclusiveMinimum must be number  components.schemas.Settings.properties.backups
```

The relevant YAML:
```
    BackupSettings:
      title: BackupSettings - Backup Settings
      description: |-
        Settings relating to automatic backups
      properties:
        enabled:
          type: boolean
          description: Enable or disable automatic backups
        interval:
          type: number
          minimum: 0
          exclusiveMinimum: true
          description: Amount of time (in hours) between automatic backups
      required:
        - enabled
        - interval
      example:
        enabled: true
        interval: 24
```
When switching back to just Ruleset 1.2.2 via `npm install @stoplight/spectral-rulesets@v1.2.2`, the linting does not flag an issue with the `exclusiveMinimum`

I hope this is helpful, and if I'm doing something dumb, please let me know!
