### ISSUE TITLE
some JsonPath don't work any more since upgrade from 5.9.2 to 6.1.0

### ISSUE THREAD

**Issue by OnimeNoKyo** [stoplightio/spectral#1920]
**Describe the bug**
Since an upgrade from 5.9.2 to 6.1.0, some given JsonPath don't work anymore

**To Reproduce**

1. Given this OpenAPI
```yaml
openapi: "3.0.0"

info:
  title: Wonderful API
  description: A super cool API that does cray stuff
  version: "1.0.0"

paths:
  /resources/{id}:
    post:
      summary: with unitary id
    parameters:
      - in: query
        name: id
        required: true
        schema:
          type: string
```
2. Given this CustomRule Set
```yaml
rules:
  http-method-no-post-on-unit-resource:
    recommended: true
    description: Post cannot be used on unitary resource (/resources/{id})
    message: "{{description}} ({{path}})"
    severity: error
    tags:
      - http method
    given: $.paths[?(/^((\/[a-z0-9\-_]+)?\/v[0-9]+)?(\/[a-z0-9\-_]+\/(?!search)[a-z0-9\-_{}]+)+$/i.test(@property))]
    then:
      - field: "@key"
        function: pattern
        functionOptions:
          match: "^(parameters|x-.*|get|put|patch|delete)$"
``` 
3. Run this CLI command
```bash
npm i --force -g @stoplight/spectral@5.9.2 &&
spectral --version &&
spectral lint example-openapi.yaml -r http-method-ruleset.yaml
```
```bash
evalmachine.<anonymous>:1
/^((/[a-z0-9-_]+)?/v[0-9]+)?(/[a-z0-9-_]+/(?!search)[a-z0-9-_{}]+)+$/i.test(_$_property)
                ^

SyntaxError: Unexpected token ')'
    at new Script (vm.js:102:7)
    at createScript (vm.js:262:10)
    at Object.runInNewContext (vm.js:303:10)
    at JSONPath._eval (C:\work\data\npm\node_modules\@stoplight\spectral-cli\node_modules\jsonpath-plus\dist\index-node-cjs.cjs:643:20)
    at C:\work\data\npm\node_modules\@stoplight\spectral-cli\node_modules\jsonpath-plus\dist\index-node-cjs.cjs:420:16
    at C:\work\data\npm\node_modules\@stoplight\spectral-cli\node_modules\jsonpath-plus\dist\index-node-cjs.cjs:576:7
    at Array.forEach (<anonymous>)
    at JSONPath._walk (C:\work\data\npm\node_modules\@stoplight\spectral-cli\node_modules\jsonpath-plus\dist\index-node-cjs.cjs:575:22)
    at JSONPath._trace (C:\work\data\npm\node_modules\@stoplight\spectral-cli\node_modules\jsonpath-plus\dist\index-node-cjs.cjs:419:10)
    at JSONPath._trace (C:\work\data\npm\node_modules\@stoplight\spectral-cli\node_modules\jsonpath-plus\dist\index-node-cjs.cjs:536:17)
jsonPath: Unexpected token ')': /^((/[a-z0-9-_]+)?/v[0-9]+)?(/[a-z0-9-_]+/(?!search)[a-z0-9-_{}]+)+$/i.test(_$_property)
```

**Expected behavior**
using v5.9.2, it's working perfectly
```bash
OpenAPI 3.x detected

c:/api-linter/samples/example-openapi.yaml
 10:10  error  http-method-no-post-on-unit-resource  Post cannot be used on unitary resource (/resources/{id}) (#/paths/~1resources~1{id}/post)  paths./resources/{id}.post

✖ 1 problem (1 error, 0 warnings, 0 infos, 0 hints)
```

**Environment (remove any that are not applicable):**
 - Library version: 6.1.0
 - OS: Windows 10

**Comment by P0lip** [comment]
Hey!
Yeah, it appears to be a bug in https://github.com/JSONPath-Plus/JSONPath - I suggest creating a ticket in their repo.
![image](https://user-images.githubusercontent.com/9273484/139479420-97f5960b-d559-498e-8491-27f94570d020.png)
We've updated the version between v5 and v6 and seems like there's some regression.

We can keep this one open to keep the track of it.

--

Frankly speaking, I'd consider moving that logic to a custom function. Having such a complex regular expression in json path expression is not particularly

**Comment by ioggstream** [comment]
Hi @P0lip ! I found that even simpler rules are not working anymore... Eg. I had to do something like that: 

```
   integer-format:
     
     given: >
-      $.[?(@.type=="integer")]
+      $.[?(@ && @.type == "integer")]
```

**Comment by P0lip** [comment]
Hey @ioggstream!
Well, that's valid. `@` points at a given value in your document, so if that value is null, a type error will be thrown.
One always had to do `@ && @.type`, previously it was just an unexpected behavior (for me, at least).
Unfortunately, there's still no formal spec around JSONPath, so well, there's no standardized approach.
Hopefully, the draft that's currently WIP is formalized soon, and we can adhere to it.

**Comment by ioggstream** [comment]
Thanks for your reply! In the jsonpath-plus demo here https://jsonpath-plus.github.io/JSONPath/demo/? the given entry doesn't seem to need `(@ && )`.

Since `?(  ..  )` implements a "query" this behavior seems to me quite peculiar: is this the spec you're referring to? https://www.ietf.org/archive/id/draft-ietf-jsonpath-base-02.html

**Comment by P0lip** [comment]
> Thanks for your reply! In the jsonpath-plus demo here https://jsonpath-plus.github.io/JSONPath/demo/? the given entry doesn't seem to need (@ && ).

They might be using an outdated version in that repl.
This is what I get for 6.0.1 
https://npm.runkit.com/jsonpath-plus
![image](https://user-images.githubusercontent.com/9273484/143019302-a546e8a8-adef-44e9-b8e8-b5ab4c2dfabe.png)

[nimma](https://github.com/p0lip/nimma), the default JSONPath expression interpreter that Spectral uses behaves similarly to jsonpath-plus in the way it handles those filter script expressions.

> Since ?( .. ) implements a "query" this behavior seems to me quite peculiar: is this the spec you're referring to? https://www.ietf.org/archive/id/draft-ietf-jsonpath-base-02.html

Yes, that's indeed the spec - it's not the exact version I saw, but I'm unsure whether there's anything much newer.

That revision of spec doesn't specify anything about the exact behavior of the existence check.
The initial [article](https://goessner.net/articles/JsonPath/) where the whole concept of JSONPath was described, does make it clear that script expressions should be "using the underlying script engine".

The draft itself tries to put some boundaries and specify how those expressions are evaluated to ensure consistency across different implementations, but it's so far unclear what the specific semantics is supposed to be.

**Comment by mikekistler** [comment]
I am also having problems with Spectral v6+ understanding JSON Paths that v5.9 handled perfectly well.

Here is a rule that works fine with v5.9.2 and not with v6.1.0:
```
rules:
  az-additional-properties-object:
    description: additionalProperties with type object is a common error.
    severity: info
    formats: ['oas2', 'oas3']
    given: $.[?(@property == "additionalProperties" && @.type == "object" && @.properties == undefined)]
    then:
      function: falsy
```

Using this test file:
```
{
  "swagger": "2.0",
  "info": {
    "title": "bug",
    "version": "0.0.1",
    "description": "bug",
    "contact": {
      "email": "foo@bar.com"
    }
  },
  "host": "foo.bar.com",
  "schemes": [ "https" ],
  "tags": [ {"name": "bug"} ],
  "paths": {},
  "definitions": {
    "Foo": {
      "type": "object",
      "properties": {
        "bar": {
          "type": "string"
        }
      },
      "additionalProperties": {
        "type": "object"
      }
    }
  }
}
```

v5.9.2 correctly reports the issue but not v6.1.0:
```
>npx @stoplight/spectral@5.9.2 lint --ruleset spectral.yaml test.json    
npx: installed 152 in 6.039s
OpenAPI 2.0 (Swagger) detected

/Users/mikekistler/Projects/stoplightio/spectral-debug/test.json
 23:30  information  az-additional-properties-object  additionalProperties with type object is a common error.  definitions.Foo.additionalProperties

✖ 1 problem (0 errors, 0 warnings, 1 info, 0 hints)

>npx @stoplight/spectral-cli@6.1.0 lint --ruleset spectral.yaml test.json
npx: installed 190 in 17.872s
No results with a severity of 'error' or higher found!

```

And I don't think this can be blamed on the new version of JSON Path Plus -- I tried out in npm.runkit as shown above and it works fine at that level.

![image](https://user-images.githubusercontent.com/85643503/144349278-7d6fdf3f-e8a6-4263-ad26-323ad174955d.png)

I really think this is a bug in Spectral v6+.
