### ISSUE TITLE
Fix example for operation-id-kebab-case

### ISSUE THREAD

**Issue by m-mohr** [stoplightio/spectral#1973]
**Chore summary**
Fix documentation example for operation-id-kebab-case at https://meta.stoplight.io/docs/spectral/ZG9jOjI1MTkw-custom-functions#options

**Tasks**

The given example doesn't work for me. I made it work like this:

```yaml
  operation-id-kebab-case:
    given: "$..operationId"
    then:
      function: pattern
      functionOptions:
        match: ^[a-z][a-z0-9\-]*$
```
