### ISSUE TITLE
binary type properties fail validation for lack of example

### ISSUE THREAD

**Issue by acabarbaye** [stoplightio/spectral#2075]
Whenever an object has a property of binary (i.e. type: string, format: binary) validation will fail with the following error message

```
 oas3-valid-schema-example  "example" property type must be string  components.schemas....
```

Although the field example is present. This is really tied to the property being of type binary; remove the "format: binary" and the specification document will pass validation.

**Comment by P0lip** [comment]
Hey @acabarbaye
Could you please provide a sample OpenAPI document I could use for the testing purposes?

**Comment by acabarbaye** [comment]
See example below of such a data model. `fileContent` is the part making the check to complain
```
    ArtefactItem:
      title: artefact Item
      description: >
        When an instance is ready, it can contain artefacts.
      type: object
      properties:
        name:
          description: Unique ID of the instance artefact.
          type: string
          readOnly: true
          example: blahblah.axf
        title:
          description: Optional human readable name of the instance artefact.
          type: string
          example: "My binary"
          nullable: true
        fileContent:
          description: artefact file
          type: string
          format: binary
          writeOnly: true
          example: "01010101001110111011"
```
