### ISSUE TITLE
Rule for enforcing all parameters to be references for AsyncAPI channels

### ISSUE THREAD

**Issue by jonaslagoni** [stoplightio/spectral#2117]
**User story.**
As a user, I want to be able to enforce that reusability should be in focus, and therefore all parameters should be references.

**Describe the solution you'd like**
I want this rule to be part of the built-in ruleset.

**Additional context**
The way I am currently enforcing it, is through the rule:

```yml
rules: 
  ...
  asyncapi-parameters-must-use-references:
    description: Channel parameters must be references
    given: $.channels.[*]
    severity: error
    resolved: false
    then:
      function: schema
      functionOptions:
        schema:
          properties:
            parameters:
              additionalProperties:
                type: object
                required:
                  - $ref
```
