### ISSUE TITLE
Rule for enforcing top-level JSON Object for AsyncAPI message payloads

### ISSUE THREAD

**Issue by jonaslagoni** [stoplightio/spectral#2119]
**User story.**
As a user, I want to enforce all message payloads to always contain a JSON object as the top-level message payload.

**Describe the solution you'd like**

I want this rule to be part of the built-in ruleset.

**Additional context**
The way I am currently enforcing it is through the rule:
```yml
rules: 
  ...
  asyncapi-message-payload-must-have-root-level-object:
    description: Message payloads must at the root be an object
    given: $.channels.[*][subscribe,publish].message..payload
    severity: error
    then:
      function: schema
      functionOptions:
        schema:
          properties:
            type:
              const: "object"
```
