### ISSUE TITLE
Add core ruleset for JSON Schema draft 2020-12

### ISSUE THREAD

**Issue by dolmen** [stoplightio/spectral#2136]
**User story.**
As a user, I want to use Spectral to validate a JSON Schema draft 2020-12 file.

I would like to be able to use a built-in ruleset.

**Describe the solution you'd like**

Spectral would provide a built-in ruleset that I could reference for validation.

**Comment by P0lip** [comment]
Hey @dolmen!
Is there any particular set of rules you'd be looking to have included?

**Comment by hjoukl** [comment]
As suggested by @P0lip on #2139 I propose to add to such a built-in ruleset:

```
---
extends: "spectral:oas"
rules:
  properties-type-object:
    description: "Objects with properties must have type: object."
    given: "$..[?(@ && @.properties)]"
    severity: error
    # must not be resolved because $ref-defined objects shall have its type
    # defined in the referenced schema, not the referencing field (and $ref 
    # must be the only property, anyway)
    resolved: false
    # type field must be defined and contain the value object
    then:
      - field: "type"
        function: defined
      - field: "type"
        function: enumeration
        functionOptions:
          values:
            - object
```

Reasoning:
The way OpenAPI/JSON Schema validation works wrt to structures with properties but no `type: object` is probably not what most users would expect (I certainly didn't):

Because IIUC a schema like

```
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "properties": {
    "number": { "type": "number" },
    "street_name": { "type": "string" }
  },
  "required": ["number"],
}
```

is not a "de facto" restriction on a JSON object i.e. the key-value mapping aka dictionary to carry the given properties. According to [JSON Schema Cort: Assertions and Instance Primitive Types](https://json-schema.org/draft/2020-12/json-schema-core.html#rfc.section.7.6.1) only those assertions are used for validating a value which belong to the "Validation Keywords" of the data type.

Which means that all of these are valid against the above schema:

Valid:

```
{
  "number": 10
}
```

Valid:
```
""
```

Valid:
```
false
```

(basically, anything - just by accidentally omitting `type: object` for a "struct")

I gather the user will usually expect "struct" data to be only treated as  valid if (required) properties are present in the instance object data model. The proposed rule thus omits an error for OpenAPI object schemas that define properties but not `type: object`.

Best, Holger
