### ISSUE TITLE
YAML null key not supported

### ISSUE THREAD

**Issue by rubensa** [stoplightio/spectral#2276]
**Describe the bug**
I'm not allowed to use the YAML **null** key.

**To Reproduce**
When I try to apply [Configuration key conflicts](https://quarkus.io/guides/config-yaml#configuration-key-conflicts) like:
```yaml
quarkus:
  http:
    cors:
      ~: true
      origins: "*"
```
I get the following problem report:
`Mapping key must be a string scalar rather than null`

**Expected behavior**
The null key should be allowed and no problem should be reported.
