### ISSUE TITLE
Percent-encoding JSON Pointers in #2511 introduced a breaking change in spectral-core and spectral-cli

### ISSUE THREAD

**Issue by dlkj** [stoplightio/spectral#2515]
**Describe the bug**

#2511 has introduced a breaking change for rule override JSON Pointers. Different minor versions of spectral-core require different rule override files.

**To Reproduce**

1. create an override with a character that could be percent encoded, for example:
```yaml
extends: ruleset.yaml
overrides:
  - files:
      - openapi.yaml#/resource:custom-method/post/requestBody
    rules:
      my-rule: off
```
2. override works with `spectral-core` 1.18.2
3. override fails with `spectral-core` 1.18.3
4. changing the override to the following fixes 1.18.3 but breaks 1.18.2. Note the changing of "`:`" to "`%3A`"
```yaml
extends: ruleset.yaml
overrides:
  - files:
      - openapi.yaml#/resource%3Acustom-method/post/requestBody
    rules:
      my-rule: off
```

**Expected behavior**

This should have been released as a breaking change, requiring a bump of the `spectral-cli` version number. Currently we have `6.6.0` of `stoplight/spectral-cli` showing both of theses behaviours depending on when it was installed from NPM (and which version of `spectral-core` was resolved.

**Environment (remove any that are not applicable):**
 - spectral-cli 6.6.0
 - Node.JS 18.16.0
 - OS: Windows 10, Ubuntu 22.04
