### ISSUE TITLE
new rules: case enforcement

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/spectral#405]
**User story.**
As an OpenAPI user, I would like the following default rules, which are not in the OpenAPI spec but are rather nice and help new users create consistent specs, and look the best in the most tools.

- camelCase for Request and Response payload
- Title Case for responses description
- PascalCase for schema names

**Is your feature request related to a problem?**
User requested these rules and they are common enough we should help make it clear how to do.

**Describe the solution you'd like**

#712 added casing as a core function, so let's show it off in our openapi ruleset. We can make it recommended: false for now to avoid it popping up everywhere, and see what feedback we get about it.

**Comment by nulltoken** [comment]
And maybe kebabCase for headers?

**Comment by philsturgeon** [comment]
This was submitted by @miller79 and it's awesome:

```
  schema-names-pascal-case:
    description: Schema names MUST be written in PascalCase
    message: "{{property}} is not PascalCase: {{error}}"
    recommended: true
    type: style
    given: "$.components.schemas.*~"
    then:
      function: pattern
      functionOptions:
        match: ^[A-Z][a-zA-Z0-9]*$
```
