### ISSUE TITLE
Extend Rules with custom properties

### ISSUE THREAD

**Issue by radicarl** [stoplightio/spectral#656]
**User story.**
We use your great linter in our CI-Pipeline to enforce that the API-Specification follow our API-Guidelines. We have a wrapper script that calls spectral and converts the json output in a human readable format. It would be great, if we could add additional information to our custom rules, which are added to the json output of each violation of this rule. We want to use this to add a link to the specific part of the guide where the rule is described.

**Describe the solution you'd like**
Defining own rules in .spectral.yml like this
```yaml
rules:
  my-rule:
    description: Some short text
    custom-fields:
       link-to-guide: http://company.com/api-guide.html#my-rule
       another-field: some value
   # ...
```
and getting the following json if the rule was violated:
```json
{
   "code":"my-rule",
   "path":[ ...  ],
   "message":"Some short text",
   "severity":0,
   "range":{ ...},
   "source":"openapi.yml",
   "link-to-guide":"http://company.com/api-guide.html#my-rule",
   "another-field":"some value"
},
```
