### ISSUE TITLE
How to check if one property or another are truthy?

### ISSUE THREAD

**Issue by okv** [stoplightio/spectral#804]
**Chore summary**
How to check if one property or another are truthy?

**Additional context**
I try to check `example` or `examples` in responses content. I thought it would be similar to xor:

```yaml
    then:
      function: or
      functionOptions:
        properties:
          - example
          - examples
```

but I got error:

```
Function or not found. Called by rule response-content-example.
```

I have feeling that a missed something in docs)

p.s. spectral is a great tool, thanks a lot for your effort.
