### ISSUE TITLE
Help in creating a Spectral JSONPath Rule

### ISSUE THREAD

**Issue by vgupta1127** [stoplightio/spectral#836]
**Chore summary**
Need help in writing a Spectral Rule

**Tasks**
I want to create a rule that iterates over each path in `paths` object of an API and see if contains `options` key

**Additional context**
Refer to a sample API : [PetStore](https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/json/petstore.json)

**Comment by vgupta1127** [comment]
**I want to iterate over each path in `paths` object and check if each path has an `options` property.**

I have created the following rule and custom function:

```
OPTIONS-in-path-rule:
    description: Each path must have OPTIONS property
    recommended: true
    formats: ["oas2", "oas3"]
    given: "$.paths.*"
    severity: error
    message: PROPERTY- {{error}}
    then: 
      function: verifyOPTIONS
```

verifyOPTIONS.js:
```
module.exports = (targetVal) => {
  
    for (i = 0; i < targetVal.length; i++) {
        if (('options' in targetVal[i]) === false) {
              return [
                {
                  message: 'OPTIONS not present in API path',
                },
              ];
          }
      }
  };

```

`targetVal[i]` is supposed to return each path in `paths` object of PetStore... **But it isn't returning each path. There is NO MATCH**

Please help me @P0lip

**Comment by P0lip** [comment]
@vgupta1127 
I believe you may not need to use custom function at all.
If I understand the problem correctly, you should be able to use `truthy` function together with `field`.

```yaml
OPTIONS-in-path-rule:
  description: Each path must have OPTIONS property
  recommended: true
  formats: ["oas2", "oas3"]
  given: "$.paths.*"
  severity: error
  message: PROPERTY- {{error}}
  then:
    field: options
    function: truthy
```

Let me know how it goes, please.
