### ISSUE TITLE
Trouble validating array examples

### ISSUE THREAD

**Issue by cbetta** [stoplightio/spectral#847]
Im having an issue trying to validate an array example. My spec is as follows.

```yml
allowed_invitee_roles:
        x-box-field-variant: 3
        type: array
        example: 
          - editor
        nullable: false
        enum:
          - editor
          - viewer
          - previewer
          - uploader
          - previewer uploader
          - viewer uploader
          - co-owner
        description: |-
          A list of the types of roles that user can be invited at
          when sharing this folder.
        items:
          type: string
```

The error I get is as follows:

```
error  valid-example-in-schemas         "allowed_invitee_roles.example" property should be equal to one of the allowed values: editor, viewer, previewer, uploader, previewer uploader, viewer uploader, co-owner. Did you mean editor?
```

I am lost as to what to do. I've tried to set the example value to `"editor"`, `[editor]` and many more, but without any luck.

**Comment by mheap** [comment]
Using alternative syntax, you're saying the following:

Must be one of: `[editor, viewer, previewer, uploader, previewer uploader, viewer uploader, co-owner]`

And you're providing `[editor]` which doesn't equal `editor`

Changing the example to be `example: editor` should resolve the issue

**Comment by cbetta** [comment]
FWIW when I set it to just `example: editor` I get this error.

```
error  valid-example-in-schemas         "allowed_invitee_roles.example" property type should be array
```

**Comment by cbetta** [comment]
I think I got it. I think the `enum` needs to be part of the `items`.

```yml
    allowed_invitee_roles:
        x-box-field-variant: 2
        type: array
        example: 
          - editor
        nullable: false
        description: |-
          A list of the types of roles that user can be invited at
          when sharing this file.
        items:
          type: string
          enum:
            - editor
            - viewer
            - previewer
            - uploader
            - previewer uploader
            - viewer uploader
            - co-owner
```
