### ISSUE TITLE
oas3-valid-content-schema-example seems to misbehave with arrays

### ISSUE THREAD

**Issue by bkabrda** [stoplightio/spectral#927]
**Describe the bug**

Given following schema:

```yaml
components:
  schemas:
    X:
      type: array
      items:
        type: string
      example:
        value:
          - "foo"
```

Validating yields error `error  oas3-valid-content-schema-example  `example` property type should be array`. When I transform it to

```yaml
components:
  schemas:
    X:
      type: array
      items:
        type: string
      example:
        - "foo"
```

I get the following warning: `warning  example-value-or-externalValue  Example should have either a `value` or `externalValue` field.`

**Expected behavior**

I think at least the first example is correct according to the openapi spec (so shouldn't yield an error), not sure about the second one.

**Environment (remove any that are not applicable):**
Using Docker image stoplight/spectral:5 (image id 38270ed7d5da).
